version: "3.7"
services:
  client:
    restart: always
    build: client/
    depends_on:
      - server
    ports:
      - '3000:3000'
  server:
    restart: always
    build: server/
    depends_on:
      - database
    ports:
      - '8000:8000'
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
